name: Inspect github context and environment
on:
  push:
  workflow_dispatch:

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump Contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          ENV_CONTEXT: ${{ toJson(env) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          echo "GITHUB_CONTEXT:\n$GITHUB_CONTEXT\n"
          echo "ENV_CONTEXT:\n$ENV_CONTEXT\n"
          echo "RUNNER_CONTEXT:\n$RUNNER_CONTEXT\n"
          echo "INPUTS_CONTEXT:\n$INPUTS_CONTEXT\n"
          echo "JOB_CONTEXT:\n$JOB_CONTEXT\n"
          echo "VARS_CONTEXT:\n$VARS_CONTEXT\n"

  printEnv:
    name: Print Environment
    runs-on: ubuntu-latest
    steps:

    - name: Set namespace for tag
      if: github.ref_type == 'tag'
      run: echo "NAMESPACE={{ github.ref_name }}" >> $GITHUB_ENV

    - name: Print env
      run: env | sort

  changedPaths:
    name: Changed paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        id: checkout
      - name: Get changed paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            changed:
              - '**'
      - name: List changed paths
        run: |
          echo "changed paths: ${{ steps.filter.outputs.changed_files }}"
