name: Public IP

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}

    - name: Get IP without external Action
      run: |
        echo $(curl -s https://api.ipify.org)

    - name: Another way to get public IP
      id: get-ip
      run: echo "ip_address=$(dig +short myip.opendns.com @resolver1.opendns.com)" >> $GITHUB_OUTPUT

    - name: Check output
      run: |
        echo ${{ steps.get-ip.outputs.ip_address }}
