name: Inspect github context and environment
on:
  push:

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  printEnv:
    name: Print Environment
    runs-on: ubuntu-latest
    steps:

    - name: Set namespace for tag
      if: github.ref_type == 'tag'
      run: echo "NAMESPACE={{ github.ref_name }}" >> $GITHUB_ENV

    - name: Print env
      run: env | sort

  changedPaths:
    name: Changed paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        id: checkout
      - name: Get changed paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            changed:
              - '**'
      - name: List changed paths
        run: |
          echo "changed paths: ${{ steps.filter.outputs.changed_files }}"
