name: GitHub Actions Demo

jobs:

  example-job:
    on: [push]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: ls ${{ github.workspace }}

  merge-job:
    on: [pull_request]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
